title: FOSSIL - Open Source Software Interest League
tagline: A blog dedicated to reviewing cat gifs
description: >- # this means to ignore newlines until "baseurl:"
  Sebuah UKM Universitas AMIKOM Yogyakarta yang digerakkan oleh para penggemar 
  teknologi dan kontributor open-source, untuk membantu mahasiswa menjadi bagian 
  dari ekosistem open-source dengan menyediakan pelatihan dan pengembangan keterampilan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://inspiring-banach-a0c406.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
disqus: 
  shortname: fossil

# Information
email: contact@fossil.or.id
discord_channel: https://discord.gg/2QhfwTt
github_username: esemkasa

# kramdown:
#   syntax_highlighter_opts: 
permalink: /:title/
# Build settings
defaults:
  - scope:
      path: assets/static/img
    values:
      image: true
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      seo:
        type: BlogPosting

sass:
  style: compressed
  sourcemap: never

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-postfiles
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
